import {TOOL_TITLES,type Activity,type Offer} from "@/lib/chat-types";
function text(value:unknown,max=240){return typeof value==="string"?value.slice(0,max):"";}
function object(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
export function secureUrl(value:unknown,endpoint:string){try{const url=new URL(text(value,2000));const origin=new URL(endpoint).origin;const origins=new Set([origin,"https://exec.cadon.io"]);return url.protocol==="https:"&&origins.has(url.origin)&&!url.username&&!url.password&&(/^\/(demo|s)\//.test(url.pathname)||url.origin==="https://exec.cadon.io")?url.toString():undefined;}catch{return undefined;}}
export function toolSummary(argumentsText:string){try{const args=object(JSON.parse(argumentsText));const parts:string[]=[];if(typeof args.budget_eur==="number"&&Number.isFinite(args.budget_eur))parts.push(new Intl.NumberFormat("en-BE",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(args.budget_eur));if(args.vehicle_type==="new"||args.vehicle_type==="used")parts.push(`${args.vehicle_type} vehicle`);if(typeof args.market==="string"&&/^[A-Z]{2}$/.test(args.market))parts.push(args.market);return parts.join(" · ");}catch{return "";}}
export function outputObject(output:unknown):Record<string,unknown>{let data=typeof output==="string"?JSON.parse(output):output;const root=object(data);if(root.structuredContent)return object(root.structuredContent);if(Array.isArray(root.content)){for(const part of root.content){const p=object(part);if(p.type==="text"&&typeof p.text==="string"){try{data=JSON.parse(p.text);return object(data);}catch{/* No invented structured result. */}}}}return root;}
export function presentTool(item:Record<string,unknown>,endpoint:string):Activity{const name=text(item.name,80),id=text(item.id,120);const base:Activity={id,name,title:TOOL_TITLES[name]||"CADON activity",status:item.error?"error":"ready",summary:toolSummary(text(item.arguments,6000))};if(item.error)return base;try{const data=outputObject(item.output);const root=typeof item.output==="string"?JSON.parse(item.output):item.output;if(object(root).isError||data.isError||data.error){base.status="error";return base;}const url=secureUrl(data.demo_url,endpoint);if(url){base.url=url;base.launchId=text(data.launch_id,120);}
 if(typeof data.question==="string"&&data.ready_for_cards===false)base.question=text(data.question,800);
 if(Array.isArray(data.offers))base.offers=data.offers.slice(0,24).map((value):Offer=>{const o=object(value);return {bankId:text(o.bank_id,80),name:text(o.bank_name,100),rate:text(o.rate,100),highlight:text(o.highlight),url:secureUrl(o.demo_url,endpoint),launchId:text(o.launch_id,120),metrics:Array.isArray(o.metrics)?o.metrics.slice(0,4).map(m=>{const metric=object(m);return {label:text(metric.label,100),value:text(metric.value,100)};}):[]};});
 if(name==="get_demo_result"){const signal=object(data.signal);base.signal=text(signal.status||data.status,80)||"Result received";if(["expired","failed","error","incomplete"].includes(base.signal))base.status="error";if(data.state==="expired"||data.reason==="launch_expired"||data.reason==="session_expired_before_completion")base.question="This secure session has expired. Create a new request.";if(data.state==="not_found")base.question="CADON could not find this session. Create a new request.";}
 }catch{base.status="error";}return base;}
