"use client";
import { useState } from "react";
import {ACCESS_EMAIL,accessEmailDraft} from "@/lib/access-email";
export default function RequestAccess(){
 const [state,setState]=useState<"idle"|"loading"|"success"|"error">("idle");const [message,setMessage]=useState("");
 const [draft,setDraft]=useState<ReturnType<typeof accessEmailDraft>|null>(null);const [copied,setCopied]=useState(false);
 return <form className="access-form" onSubmit={async e=>{e.preventDefault();if(state==="loading")return;const data=Object.fromEntries(new FormData(e.currentTarget));setDraft(accessEmailDraft(data));setCopied(false);setState("loading");setMessage("");try{const r=await fetch("/api/request-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const body=await r.json();if(!r.ok||body.ok!==true)throw new Error(body.error||"Unable to send your request. Please use the email option below.");setState("success");setMessage("Request received. We’ll be in touch about access.");}catch(err){setState("error");setMessage(err instanceof Error?err.message:"Unable to send your request. Please use the email option below.");}}}>
 {state==="success"?<div className="form-success" role="status"><h3>Thank you for your interest.</h3><p>{message}</p></div>:<><div className="form-grid"><label>Work email<input required name="email" type="email" autoComplete="email" maxLength={254} placeholder="you@company.com"/></label><label>Company<input required name="company" autoComplete="organization" maxLength={120} placeholder="Company name"/></label><label>Role<input required name="role" autoComplete="organization-title" maxLength={100} placeholder="Your role"/></label><label>I’m interested in<select name="audience"><option>Financial institution</option><option>AI platform or developer</option><option>Other</option></select></label></div><label>What would you like to use CADON for?<textarea name="useCase" required rows={3} maxLength={1500} placeholder="Tell us about the workflow you have in mind."/></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><p className="form-note">We’ll use these details to respond to your request. Please don’t include financial or identity information. <a href="/privacy">Privacy details</a>.</p><button className="button" disabled={state==="loading"} type="submit">{state==="loading"?"Sending request…":"Request access"}</button><p role={state==="error"?"alert":"status"} className="form-message">{state==="error"&&message}</p></>}
 {state==="error"&&draft&&<div className="access-email-fallback"><p>Your request has not been delivered. Your details are still in the form.</p><a className="button secondary" href={draft.href}>Send request by email</a><p className="form-note">This opens an email draft to {ACCESS_EMAIL}. Send it from your email app to complete your request.</p><button type="button" className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(`To: ${ACCESS_EMAIL}\nSubject: CADON access request\n\n${draft.body}`);setCopied(true);}catch{setMessage(`Copy your details from the form and email ${ACCESS_EMAIL}.`);}}}>{copied?"Request copied":"Copy email request"}</button></div>}
 </form>
}
