/* eslint-disable @typescript-eslint/no-require-imports -- CJS harness intercepts server-only imports for offline boundary tests. */
/* Offline boundary tests. Upstream Responses fixtures never ship in application routes. */
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const Module=require('node:module');const ts=require('typescript');
const original=Module._load;let cookie='test-access-cookie';
Module._load=function(name,parent,isMain){if(name==='server-only')return {};if(name==='next/headers')return {cookies:async()=>({get:()=>cookie?{value:cookie}:undefined})};if(name==='next/server')return {NextResponse:{json:(body,options)=>Response.json(body,options)},after:fn=>fn()};if(name==='@/lib/demo-auth')return {COOKIE_NAME:'cadon_demo_session',hasDemoAccess:async()=>Boolean(cookie)};if(name.startsWith('@/'))name=path.resolve(__dirname,'../src',name.slice(2)+'.ts');return original.call(this,name,parent,isMain)};
require.extensions['.ts']=function(mod,file){mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,file)};
process.env.CADON_DEMO_SESSION_SECRET='offline-test-secret-00000000000000000000';delete process.env.UPSTASH_REDIS_REST_URL;delete process.env.UPSTASH_REDIS_REST_TOKEN;
const {newChatState,sealChatState,openChatState}=require('../src/lib/chat-state.ts');const {presentTool,secureUrl,toolSummary}=require('../src/lib/chat-output.ts');const {jsonEvents}=require('../src/lib/sse.ts');const {POST}=require('../src/app/api/demo-chat/route.ts');
const req=(data,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/demo-chat',{method:'POST',headers:{host:'localhost:3000',origin,'content-type':'application/json'},body:JSON.stringify(data)});
function stream(events){const data=events.map(e=>'data: '+JSON.stringify(e)+'\r\n\r\n').join('');const bytes=new TextEncoder().encode(data);return new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close()}})}
async function collect(response){const events=[];for await(const e of jsonEvents(response.body))events.push(e);return events;}
(async()=>{
 const state=newChatState(cookie);const sealed=sealChatState(state);assert.equal(openChatState(sealed,cookie).owner,state.owner);assert.throws(()=>openChatState(sealed,'different-cookie'));assert.throws(()=>openChatState(sealed.slice(0,-8)+'tampered',cookie));assert.throws(()=>openChatState(sealChatState({...state,expires:0}),cookie));
 const values=[];for await(const e of jsonEvents(stream([{delta:'€25,000'},{done:true}])))values.push(e);assert.equal(values[0].delta,'€25,000');await assert.rejects(async()=>{for await(const e of jsonEvents(new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: {'));c.close()}})))void e});
 assert.equal(secureUrl('https://evil.test/demo/1','https://cadon-demo.fly.dev/mcp'),undefined);assert.equal(secureUrl('https://cadon-demo.fly.dev/account','https://cadon-demo.fly.dev/mcp'),undefined);assert.ok(secureUrl('https://cadon-demo.fly.dev/demo/car?launch_id=abc','https://cadon-demo.fly.dev/mcp'));assert.equal(secureUrl('https://cadon-demo.fly.dev.evil.test/demo/1','https://cadon-demo.fly.dev/mcp'),undefined);assert.equal(toolSummary('{"query":"private content","preflight_token":"secret"}'),'');
 const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'../docs/mcp-offer-fixture.json'),'utf8'));assert.equal(presentTool({id:'offers',name:'show_car_loan_bank_options',output:JSON.stringify(fixture.output)},'https://cadon-demo.fly.dev/mcp').offers.length,10);
 const expired=presentTool({id:'expired',name:'get_demo_result',output:JSON.stringify({status:'incomplete',state:'expired',reason:'launch_expired'})},'https://cadon-demo.fly.dev/mcp');assert.equal(expired.status,'error');assert.match(expired.question,/expired/);
 assert.equal(presentTool({id:'x',name:'get_demo_result',error:'private server traceback'},'https://cadon-demo.fly.dev/mcp').status,'error');assert.equal(presentTool({id:'x',name:'get_demo_result',output:JSON.stringify({isError:true,content:[{type:'text',text:'private error'}]})},'https://cadon-demo.fly.dev/mcp').status,'error');assert.equal(presentTool({id:'x',name:'get_demo_result',output:'not json'},'https://cadon-demo.fly.dev/mcp').status,'error');
 assert.equal((await POST(req({message:'hello'},'https://evil.test'))).status,403);cookie='';assert.equal((await POST(req({message:'hello'}))).status,401);cookie='test-access-cookie';delete process.env.OPENAI_API_KEY;assert.equal((await POST(req({message:'hello'}))).status,503);process.env.OPENAI_API_KEY='offline-fixture-key';assert.equal((await POST(req({message:'contact me person@example.com'}))).status,400);assert.equal((await POST(req({message:'x'.repeat(33000)}))).status,400);
 const pending={id:'approve_1',name:'get_demo_result',arguments:JSON.stringify({launch_id:'other',wait_seconds:0})};const approvalState=sealChatState({...state,pending:[pending],responseId:'resp_old',launches:['mine']});assert.equal((await POST(req({state:approvalState,approval:{id:'approve_1',approve:true}}))).status,400);assert.equal((await POST(req({state:approvalState,approval:{id:'invented',approve:true}}))).status,400);assert.equal((await POST(req({state:approvalState,message:'bypass approval'}))).status,409);
 const slow=sealChatState({...state,pending:[{...pending,arguments:JSON.stringify({launch_id:'mine'})}],launches:['mine']});assert.equal((await POST(req({state:slow,approval:{id:'approve_1',approve:true}}))).status,400);
 let upstreamBody;global.fetch=async(url,opts)=>{assert.equal(url,'https://api.openai.com/v1/responses');upstreamBody=JSON.parse(opts.body);return new Response(stream([{type:'response.created',response:{id:'resp_fixture'}},{type:'response.output_text.delta',delta:'Which country?'},{type:'response.output_item.done',item:{type:'mcp_approval_request',id:'ap_fixture',name:'prepare_cadon_context',arguments:'{"query":"I need €25,000 for a car"}'}},{type:'response.completed',response:{id:'resp_fixture'}}]),{status:200})};
 const events=await collect(await POST(req({message:'I need €25,000 for a car'})));assert.equal(events.find(e=>e.type==='text').delta,'Which country?');assert.deepEqual(upstreamBody.tools[0].require_approval,{never:{tool_names:['list_cadon_demo_scenarios','prepare_cadon_context','get_cadon_conversation_guide']}});assert.equal(upstreamBody.tools[0].allowed_tools.includes('resume_cadon_session'),false);assert.equal(upstreamBody.max_tool_calls,6);const done=events.find(e=>e.type==='done');const decoded=openChatState(done.state,cookie);assert.equal(decoded.pending[0].id,'ap_fixture');assert.equal(decoded.responseId,'resp_fixture');
 global.fetch=async()=>new Response(null,{status:503});const failed=await collect(await POST(req({state:done.state,approval:{id:'ap_fixture',approve:true}})));assert.ok(failed.some(e=>e.type==='error'));const failedState=openChatState(failed.find(e=>e.type==='done').state,cookie);assert.equal(failedState.pending[0]?.id,'ap_fixture','Failed upstream request must preserve approval for retry');
 for(const [failure,expected] of [[{code:'insufficient_quota'},/billing/],[{code:'server_error',message:'MCP tool discovery failed private-secret'},/MCP/],[{code:'model_not_found'},/configured model/],[{code:'server_error'},/temporarily/]]){global.fetch=async()=>new Response(stream([{type:'response.created',response:{id:'resp_failure'}},{type:'response.failed',response:{error:failure}}]),{status:200});const result=await collect(await POST(req({message:'hello'})));assert.match(result.find(e=>e.type==='error').message,expected);assert.ok(!JSON.stringify(result).includes('private-secret'));}
 global.fetch=async()=>Response.json({error:{code:'insufficient_quota'}},{status:429});assert.match((await collect(await POST(req({message:'hello'})))).find(e=>e.type==='error').message,/billing/);
 const {POST:requestAccess}=require('../src/app/api/request-access/route.ts');const {accessEmailDraft}=require('../src/lib/access-email.ts');
 const lead={email:'test@example.test',company:'Example',role:'Tester',useCase:'Demo & integration?',audience:'Other'};const leadReq=(data)=>new Request('http://localhost:3000/api/request-access',{method:'POST',headers:{host:'localhost:3000',origin:'http://localhost:3000','content-type':'application/json'},body:JSON.stringify(data)});
 global.fetch=async()=>Response.json({success:'true'});assert.equal((await requestAccess(leadReq(lead))).status,200);
 global.fetch=async()=>Response.json({success:false,message:'Please activate your form'});const inactive=await requestAccess(leadReq(lead));assert.equal(inactive.status,502);assert.match((await inactive.json()).error,/activation/);
 global.fetch=async()=>{throw new Error('private delivery secret')};const unavailable=await requestAccess(leadReq(lead));assert.equal(unavailable.status,502);assert.match((await unavailable.json()).error,/Send request by email/);
 const draft=accessEmailDraft(lead);const mail=new URL(draft.href);assert.equal(mail.pathname,'nathnael.eb@outlook.com');assert.equal(mail.searchParams.get('body'),draft.body);assert.match(draft.body,/Demo & integration\?/);
 console.log('PASS: encrypted state, tamper/ownership/expiry, chunked SSE, trusted URLs, sanitized errors, origin/auth/config, body and PII limits, pending approvals, owned status, timeout bound, native MCP request and upstream failure retry.');
})().catch(e=>{console.error(e);process.exitCode=1});
